theme: jekyll-theme-cayman
title: Saki's Blog
header-img: img/post-bg-rwd.jpg 
description: "屠龙少女的日常杂记"
keyword: "machine learning, deep leaarning, recommendation system"
url: "https://sakixiong.github.io"
sidebar: true 
sidebar-about-description: "学习生活一个都不落"
sidebar-avatar:/img/avatar-m.JPG 
