title: Saki's Blog
description: 不积跬步无以至千里.
show_downloads: false

baseurl: "/sakixiong.github.io" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://saki-xiong.github.io" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: sakixiong
image: /thumbnail-jumbo.png
twitter:
  username: sakixiong

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['now', 'about', 'contact']
