# User config
author: "sakixiong"
tagline: "notes from saki"
description: "Saki's personal notebooks"
keywords: "leaning"
email: "smartxiaoxiong@163.com"
github: "https://github.com/saki-xiong"

# Site config
baseurl: /sakixiong.github.io
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
